sudo: false
language: node_js
node_js:
  - 14
cache: npm
branches:
  only:
    - master # build master branch only
install: # 解决yarn报错问题
  - yarn
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
